"""
schemas package initialization.
"""

from adaptive_rag.schemas.chunk import Chunk, ChunkingMetadata, ChunkMetadata, ChunkProvenance
from adaptive_rag.schemas.config import (
    BM25RetrievalConfig,
    FEATURE_GROUPS,
    STRATEGY_ORDER,
    ChunkingConfig,
    ContextConfig,
    DenseRetrievalConfig,
    EmbeddingConfig,
    EvaluationConfig,
    GenerationConfig,
    HybridRetrievalConfig,
    IndexConfig,
    IngestionConfig,
    RerankerConfig,
    RetrievalConfig,
    RoutingConfig,
    StrategyName,
)
from adaptive_rag.schemas.document import (
    Document,
    DocumentMetadata,
    Element,
    ElementContent,
    ElementType,
    ExtractionIssue,
    ExtractionReport,
    Page,
    Provenance,
    Section,
)
from adaptive_rag.schemas.experiment import (
    EVAL_SPLITS,
    ErrorInfo,
    EvaluationExample,
    EvaluationReport,
    ExperimentConfig,
    ExperimentTrace,
    MetricValue,
    ReferenceInfo,
    SectionRef,
)
from adaptive_rag.schemas.generation import ContextChunk, GenerationRequest, GenerationResult, TokenUsage
from adaptive_rag.schemas.retrieval import RetrievalMetadata, RetrievalResponse, RetrievalResult
from adaptive_rag.schemas.routing import (
    EscalationDecision,
    QueryFeatures,
    QuestionType,
    RoutingDecision,
    RoutingTrace,
    StrategyEvidence,
    SufficiencyDecision,
    SufficiencySignal,
)

__all__ = [
    "BM25RetrievalConfig",
    "Chunk",
    "ChunkMetadata",
    "ChunkProvenance",
    "ChunkingConfig",
    "ChunkingMetadata",
    "ContextChunk",
    "ContextConfig",
    "DenseRetrievalConfig",
    "Document",
    "DocumentMetadata",
    "Element",
    "ElementContent",
    "ElementType",
    "EmbeddingConfig",
    "ErrorInfo",
    "EscalationDecision",
    "EvaluationConfig",
    "EVAL_SPLITS",
    "EvaluationExample",
    "EvaluationReport",
    "ExperimentConfig",
    "ExperimentTrace",
    "ExtractionIssue",
    "ExtractionReport",
    "FEATURE_GROUPS",
    "GenerationConfig",
    "GenerationRequest",
    "GenerationResult",
    "HybridRetrievalConfig",
    "IndexConfig",
    "IngestionConfig",
    "MetricValue",
    "Page",
    "Provenance",
    "QueryFeatures",
    "QuestionType",
    "ReferenceInfo",
    "RerankerConfig",
    "RetrievalConfig",
    "RetrievalMetadata",
    "RetrievalResponse",
    "RetrievalResult",
    "RoutingConfig",
    "RoutingDecision",
    "RoutingTrace",
    "STRATEGY_ORDER",
    "Section",
    "SectionRef",
    "StrategyEvidence",
    "StrategyName",
    "SufficiencyDecision",
    "SufficiencySignal",
    "TokenUsage",
]
