"""
schemas.generation
------------------
Data contracts for context formatting, generator requests, and answer results.
"""

from typing import Any, Literal
from pydantic import BaseModel, ConfigDict, Field

from adaptive_rag.schemas.config import GenerationConfig


class TokenUsage(BaseModel):
    """Token consumption reported by the generation provider."""

    model_config = ConfigDict(extra="forbid")

    input_tokens: int = 0
    output_tokens: int = 0
    total_tokens: int = 0
    reasoning_tokens: int | None = None


class ContextChunk(BaseModel):
    """A single context block formatted for LLM consumption."""

    model_config = ConfigDict(extra="forbid")

    source_index: int  # 1-based index matching "[Source N]"
    chunk_id: str
    document_id: str
    doc_title: str
    section_path: list[str]
    page_start: int | None = None
    page_end: int | None = None
    score: float
    rank: int
    token_count: int
    text: str


class GenerationRequest(BaseModel):
    """Structured prompt request passed to the generator."""

    model_config = ConfigDict(extra="forbid")

    query: str
    context: list[ContextChunk]
    system_instruction: str
    generation_config: GenerationConfig
    metadata: dict[str, Any] = Field(default_factory=dict)


class GenerationResult(BaseModel):
    """Structured answer generated by the LLM."""

    model_config = ConfigDict(extra="forbid")

    answer: str
    source_chunk_ids: list[str] = Field(default_factory=list)  # Extracted from [Source N]
    model: str
    usage: TokenUsage
    latency_ms: float
    finish_reason: str | None = None
    status: Literal["ok", "empty_answer"] = "ok"
    generator_version: str
    prompt_version: str
    metadata: dict[str, Any] = Field(default_factory=dict)
